import React from 'react'

type TermsSection = {
  title: string
  paragraphs?: string[]
  highlights?: { label: string; body: string }[]
}

const TERMS_SECTIONS: TermsSection[] = [
  {
    title: 'Overview',
    paragraphs: [
      'Consum transforms self-improvement content into actionable habit blueprints. By accessing Consum, you confirm that you are at least 16 years old and agree to use the service responsibly.',
    ],
    highlights: [
      {
        label: 'AI Disclaimer',
        body: 'Blueprints are generated by AI for informational purposes only. Evaluate all advice independently—Consum is not liable for outcomes that result from AI guidance.',
      },
    ],
  },
  {
    title: 'Accounts',
    paragraphs: [
      'Provide accurate signup information, including billing details for paid plans. You are responsible for keeping your credentials secure and for all activity that occurs under your account.',
    ],
  },
  {
    title: 'Free & Paid Plans',
    paragraphs: [
      'The free plan offers limited features, while paid subscriptions unlock extended access and higher usage limits. You may cancel at any time. We reserve the right to adjust plan features or pricing with 30 days’ notice via email.',
    ],
  },
  {
    title: 'Data Collection',
    paragraphs: [
      'We collect personal data such as email addresses, usage telemetry, and billing metadata to deliver and improve the service. We also process goals, habits, and submitted text through Google Gemini AI to generate blueprints. We do not sell your personal data.',
      'For details on how we collect, store, and handle information—including GDPR rights—please review the Privacy Policy.',
    ],
  },
  {
    title: 'User Content & GDPR Compliance',
    paragraphs: [
      'You retain ownership of the content you submit and grant Consum a license to process it for blueprint generation. Only submit material you have rights to and that complies with applicable laws.',
      'Consum complies with GDPR requirements and supports user rights outlined in the Privacy Policy.',
    ],
    highlights: [
      {
        label: 'Acceptable Use',
        body: 'Do not abuse, reverse engineer, or use Consum for illegal or harmful purposes. We may suspend or terminate accounts that violate these terms.',
      },
    ],
  },
  {
    title: 'Updates to Terms',
    paragraphs: [
      'We may update these Terms periodically. Material updates will be communicated via email. Continued use after updates constitutes acceptance of the revised Terms.',
    ],
  },
  {
    title: 'Governing Law & Liability',
    paragraphs: [
      'These Terms are governed by the laws of Poland. To the fullest extent permitted by law, Consum’s total liability is limited to the greater of €50 or the amount paid in the preceding 12 months. We are not liable for AI output errors, service interruptions, data loss, or actions by third parties.',
      'Contact us at support@consum.app with questions about these Terms.',
    ],
  },
]

export const TermsOfService: React.FC = () => {
  return (
    <div className="bg-background px-4 py-16 text-foreground sm:px-6 lg:px-8">
      <div className="mx-auto max-w-3xl space-y-10">
        <header className="space-y-4 rounded-3xl border border-border/50 bg-card/80 p-8">
          <div>
            <p className="text-sm uppercase tracking-wide text-primary">Terms of Service</p>
            <h1 className="mt-2 text-3xl font-semibold">Consum Terms of Service</h1>
          </div>
          <dl className="grid gap-4 text-sm text-muted-foreground sm:grid-cols-2">
            <div>
              <dt className="font-semibold text-foreground">Effective Date</dt>
              <dd>December 2, 2025</dd>
            </div>
            <div>
              <dt className="font-semibold text-foreground">Service URL</dt>
              <dd>https://consum.app</dd>
            </div>
          </dl>
          <p className="text-sm text-muted-foreground">
            By using Consum you agree to these legally binding terms. Please review them carefully before continuing to use the platform.
          </p>
        </header>

        <div className="space-y-12">
          {TERMS_SECTIONS.map((section) => (
            <section key={section.title} className="space-y-4">
              <h2 className="text-2xl font-semibold text-foreground">{section.title}</h2>
              {section.paragraphs?.map((paragraph) => (
                <p key={paragraph} className="text-base text-muted-foreground">
                  {paragraph}
                </p>
              ))}
              {section.highlights && (
                <div className="space-y-3 rounded-2xl border border-border/60 bg-background/80 p-4 text-sm">
                  {section.highlights.map((highlight) => (
                    <div key={highlight.label} className="space-y-1">
                      <p className="font-semibold text-foreground">{highlight.label}</p>
                      <p className="text-muted-foreground">{highlight.body}</p>
                    </div>
                  ))}
                </div>
              )}
            </section>
          ))}
        </div>
      </div>
    </div>
  )
}
